// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzauxphllnqvpxngcuac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6YXV4cGhsbG5xdnB4bmdjdWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjMyNjUsImV4cCI6MjA3MjkzOTI2NX0.ckIgmfG9MWzFwZ2G0Up-HltI3gVgoLEu4rq0raVVERM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});